# Generated by Django 4.2 on 2024-02-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbasket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
